FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/target/core-service-0.1.0.jar /app/core-service.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/core-service.jar"]
